spring:
  application:
    name: spring-batch-practice
  server:
    port: 8080

  datasource-meta:
    driver-class-name: org.mariadb.jdbc.Driver
    jdbc-url: jdbc:mariadb://localhost:3306/meta_db?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: user
    password: user

  datasource-data:
    driver-class-name: org.mariadb.jdbc.Driver
    jdbc-url: jdbc:mariadb://localhost:3306/data_db?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: user
    password: user

  batch:
    job:
      enabled: false
#   always를 설정하면 batch 설정에서 jdbc를 통해 테이블을 생성하며 생성 쿼리는 연결된 DB를 파악한 뒤 자동으로 찾지만, 혹시 찾지 못하거나 커스텀을 원하는 경우 classpath값을 부여할 수 있습니다.
    jdbc:
      initialize-schema: always
      schema: classpath:org/springframework/batch/core/schema-mariadb.sql

